//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyBroker_DBS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ResourceDescription
    {
        [Key]
        public int DescriptionId { get; set; }
        public int ResourceId { get; set; }
        public int CompanyId { get; set; }
        public string Description { get; set; }
    
        public virtual CompanyResource CompanyResource { get; set; }
    }
}
